#两处需要修改（部署），active和配置文件里的minio
server:
  port: 9030

spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rs.db.host}/rs?allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true&characterencoding=utf8mb4&zeroDateTimeBehavior=convertToNull
    username: ${rs.db.username}
    password: ${rs.db.password}
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 50MB

  ssl:
    key-store: classpath:kuril.site.pfx
    key-store-password: n5pep5ry64
    key-store-type: PKCS12 # pfx 类型的证书对应是 PKCS12
    enabled: true
    client-auth: none

my:
  minio:
    access-key: ${rs.minio.access-key}
    secret-key: ${rs.minio.secret-key}
    ip_addr: ${rs.minio.ip_addr}
    bucketName: ${rs.minio.bucketName}
    filePath: ${rs.minio.filePath}
#  web:
#    cors:
#      allow-credentials: true
#      allowed-origins: "*"
#      allowed-methods: "GET,POST,PUT,DELETE"
#      allowed-headers: "*"
